---
- hosts: windows
  vars:
    calyptia_fluentd_version: "1.0.0"
    eventlog_bencher_version: "v0.4.1.0"
    calyptia_fluentd_repo: "calyptia-fluentd.s3.us-east-2.amazonaws.com/1/windows"
  tasks:
    - name: Copy local modified version for testing
      win_copy:
        src: "{{ local_package }}"
        dest: C:\calyptia-fluentd.msi
      when: local_package != "no"
    - name: Install local calyptia-fluentd for testing
      win_package:
        path="c:\\calyptia-fluentd.msi"
        arguments="/q"
      when: local_package != "no"
    - name: Install calyptia-fluentd
      win_package:
        path="https://{{ calyptia_fluentd_repo }}/calyptia-fluentd-{{ calyptia_fluentd_version }}-x64.msi"
        Product_Id="89641f88-2289-42ff-aed0-e7b6ae6c0fe2"
        arguments="/q"
      when: local_package == "no"
    - name: Copy collector configurations
      win_copy:
        src: "./config/{{ item }}"
        dest: "C:\\opt\\calyptia-fluentd\\{{ item }}"
      with_items:
        - fluent-collector.conf
        - fluent-collector-with-tailing.conf
    - name: Copy collector with tailing configuration
      win_copy:
        src: ./config/fluent-collector-with-tailing.conf
        dest: C:\opt\calyptia-fluentd\fluent-collector-with-tailing.conf
    - name: Check EventLog benchmarking tool existence
      win_stat:
        path: C:\tools\EventLogBencher\EventLogBencher.exe
      register: eventlog_bencher_check
    - name: Install EventLog benchmarking tool
      win_get_url:
        url: https://github.com/fluent-plugins-nursery/EventLogBencher/releases/download/{{ eventlog_bencher_version }}/EventLogBencher.zip
        dest: C:\terraform\EventLogBencher.zip
      when: not eventlog_bencher_check.stat.exists
    - name: Decompress EventLog benchmark tool zip file
      win_unzip:
        src: C:\terraform\EventLogBencher.zip
        dest: C:\tools\EventLogBencher
        delete_archive: yes
      when: not eventlog_bencher_check.stat.exists
    - name: Check Appending file benchmarking tool existence
      win_stat:
        path: C:\tools\FileLoggingBencher\FileLoggingBencher.exe
      register: appending_file_bencher_check
    - name: Install Appending file benchmarking tool
      win_get_url:
        url: https://github.com/fluent-plugins-nursery/EventLogBencher/releases/download/{{ eventlog_bencher_version }}/FileLoggingBencher.zip
        dest: C:\terraform\FileLoggingBencher.zip
      when: not appending_file_bencher_check.stat.exists
    - name: Decompress appending file benchmark tool zip file
      win_unzip:
        src: C:\terraform\FileLoggingBencher.zip
        dest: C:\tools\FileLoggingBencher
        delete_archive: yes
      when: not appending_file_bencher_check.stat.exists
    - name: Check Process Explorer existence
      win_stat:
        path: C:\tools\procexp64.exe
      register: proc_exp_check
    - name: Install Process Explorer tool
      win_get_url:
        url: https://download.sysinternals.com/files/ProcessExplorer.zip
        dest: C:\terraform\ProcessExplorer.zip
      when: not proc_exp_check.stat.exists
    - name: Decompress Process Explorer zip file
      win_unzip:
        src: C:\terraform\ProcessExplorer.zip
        dest: C:\tools
        delete_archive: yes
      when: not proc_exp_check.stat.exists
    # Just for creating benchmark channel
    - name: Create Benchmark channel
      win_shell: C:\tools\EventLogBencher\EventLogBencher.exe wait -w 0 -t 1 -l 512
    - name: Copy counters.txt
      win_copy:
        src: ./config/counters.txt
        dest: C:\tools\counters.txt
    - name: Copy benchmark scripts
      win_copy:
        src: "./config/{{ item }}"
        dest: "C:\\tools\\{{ item }}"
      with_items:
        - bytes-message-bench.ps1
        - bytes-and-tailing-bench.ps1
    - name: Copy socket stat script
      win_copy:
        src: ./config/socket-count.ps1
        dest: C:\tools\socket-count.ps1
    - name: Change the hostname to new_hostname
      win_hostname:
        name: fluentd-winserv
      register: win_hostname
    - name: Reboot
      win_reboot:
      when: win_hostname.reboot_required
