---
- hosts: aggregator
  tasks:
    - name: Copy https-benchmark-server tarball
      copy:
        src: ./config/https-benchmark-server.tar.gz
        dest: /home/{{ ansible_env.USER }}/https-benchmark-server.tar.gz
        mode: 0644
    - name: https-benchmark-server location directory
      become: true
      file: path=/opt/https-benchmark-server state=directory owner=root group=root mode=0755
    - name: Unarchive https-benchmark-server tarball
      become: true
      unarchive:
        src: /home/{{ ansible_env.USER }}/https-benchmark-server.tar.gz
        dest: /opt/https-benchmark-server
        remote_src: true
    - name: Copy https-benchmark-server Unit file
      become: true
      copy:
        src: ./config/https-benchmark-server.service
        dest: /usr/lib/systemd/system/
        mode: 0644
    - name: start https-benchmark-server as simple service
      become: yes
      systemd:
        name: https-benchmark-server
        state: started
        daemon_reload: yes
        enabled: true