---
- hosts: collector
  tasks:
    - name: Generating baseline tailing benchmark w/ td-agent-bit
      shell: rate-tailing-bench -s 300 -r 0 -n td-agent-bit
      async: 1200
      poll: 30
    - name: Generating 5000 lines/sec tailing benchmark w/ td-agent-bit
      shell: rate-tailing-bench -s 300 -r 5000 -n td-agent-bit
      async: 1200
      poll: 30
    - name: Generating 10000 lines/sec tailing benchmark w/ td-agent-bit
      shell: rate-tailing-bench -s 300 -r 10000 -n td-agent-bit
      async: 1200
      poll: 30
    - name: Generating 100000 lines/sec tailing benchmark w/ td-agent-bit
      shell: rate-tailing-bench -s 300 -r 100000 -n td-agent-bit
      async: 1200
      poll: 30
    - name: Generating 300000 lines/sec tailing benchmark w/ td-agent-bit
      shell: rate-tailing-bench -s 300 -r 300000 -n td-agent-bit
      async: 1200
      poll: 30
    - name: Find benchmarking result files
      find:
        paths: /home/{{ ansible_env.USER }}/
        patterns: [ '*.tsv' ]
      register: file_list

    - name: fetch result files in directory
      fetch:
        src: "{{ item.path }}"
        dest: ./output/
      with_items: "{{ file_list.files }}"
