---
- hosts: aggregator
  vars_files:
    - version.yml
  tasks:
    - name: Download td-agent
      get_url:
        url: "http://packages.treasuredata.com.s3.amazonaws.com/4/redhat/7/x86_64/td-agent-{{ td_agent_version }}.el7.x86_64.rpm"
        dest: "/home/{{ ansible_env.USER }}/td-agent-{{ td_agent_version }}.el7.x86_64.rpm"
    - name: Install td-agent
      become: true
      yum:
        name: /home/{{ ansible_env.USER }}/td-agent-{{ td_agent_version }}.el7.x86_64.rpm
        state: present
    - name: Copy aggregator configuration
      become: true
      copy:
        src: ./config/fluent-aggregator.conf
        dest: /etc/td-agent/td-agent.conf
    - name: Copy certificates
      become: true
      copy:
        src: ./config/certs/{{ item }}
        dest: /etc/ssl/certs/{{ item }}
      with_items:
        - ca_key.pem
        - ca_cert.pem
    - name: Make sure a td-agent service is restarted
      become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: td-agent
