---
- hosts: collector
  vars_files:
    - version.yml
  tasks:
    - name: install Calyptia-Fluentd GPG key
      become: yes
      rpm_key:
        state: present
        key: https://calyptia-fluentd.s3.us-east-2.amazonaws.com/GPG-KEY-calyptia-fluentd.asc
    - name: Download calyptia-fluentd
      get_url:
        url="https://{{ calyptia_fluentd_repo }}/calyptia-fluentd-1.0.0-1.el8.x86_64.rpm"
        dest="/home/{{ ansible_env.USER }}/calyptia-fluentd-{{ calyptia_fluentd_version }}.el8.x86_64.rpm"
    - name: Install calyptia-fluentd
      become: true
      yum:
        name: /home/{{ ansible_env.USER }}/calyptia-fluentd-{{ calyptia_fluentd_version }}.el8.x86_64.rpm
        state: present
    - name: Copy collector configuration
      become: true
      copy:
        src: ./config/fluent-collector.conf
        dest: /etc/calyptia-fluentd/calyptia-fluentd.conf
    - name: Copy certificates
      become: true
      copy:
        src: ./config/certs/ca_cert.pem
        dest: /etc/ssl/certs/ca_cert.pem
    - name: Make sure a calyptia-fluentd service is stopped
      become: true
      systemd:
        state: stopped
        daemon_reload: yes
        name: calyptia-fluentd
    - name: install EPEL GPG key
      become: yes
      rpm_key:
        state: present
        key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8"
    - name: Enable EPEL
      become: true
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
    - name: Install syslog-ng
      become: true
      yum:
        name: syslog-ng
        state: present
    - name: Install Development tools
      become: true
      yum:
        name:
          - "@Development tools"
        state: present
    - name: Install psmisc package
      become: true
      yum:
        name:
          - psmisc
        state: present
    - name: Install python3-psutil package
      become: true
      yum:
        name:
          - python38-psutil
        state: present
    - name: Add configuration for receiving rsyslog messages
      become: true
      lineinfile:
       path: /etc/rsyslog.conf
       line: "{{ item }}"
       state: present
      with_items:
        - '$ModLoad imudp'
        - '$UDPServerRun 514'
        - '$ModLoad imtcp'
        - '$InputTCPServerRun 514'
    - name: Restart rsyslog
      become: true
      systemd:
        name: rsyslog
        daemon_reload: yes
        state: restarted
    - name: Copy monitoring script
      become: true
      copy:
        src: ./config/monitor.py
        dest: /usr/local/bin/monitor
        mode: 0755
    - name: Copy benchmarking script
      become: true
      copy:
        src: ./config/rate-syslog-bench.sh
        dest: /usr/local/bin/rate-syslog-bench
        mode: 0755
