---
- hosts: collector
  vars_files:
    - version.yml
  tasks:
    - name: Download td-agent
      get_url:
        url: "http://packages.treasuredata.com.s3.amazonaws.com/3/redhat/7/x86_64/td-agent-{{ td_agent_version }}.el7.x86_64.rpm"
        dest: "/home/{{ ansible_env.USER }}/td-agent-{{ td_agent_version }}.el7.x86_64.rpm"
    - name: Install td-agent
      become: true
      yum:
        name: /home/{{ ansible_env.USER }}/td-agent-{{ td_agent_version }}.el7.x86_64.rpm
        state: present
    - name: Copy collector configuration
      become: true
      copy:
        src: ./config/fluent-collector.conf
        dest: /etc/td-agent/td-agent.conf
    - name: Copy certificates
      become: true
      copy:
        src: ./config/certs/ca_cert.pem
        dest: /etc/ssl/certs/ca_cert.pem
    - name: Make sure a td-agent service is stopped
      become: true
      systemd:
        state: stopped
        daemon_reload: yes
        name: td-agent
    - name: Enable EPEL
      become: true
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: Install syslog-ng
      become: true
      yum:
        name: syslog-ng
        state: present
    - name: Install Development tools
      become: true
      yum:
        name:
          - "@Development tools"
        state: present
    - name: Install psmisc package
      become: true
      yum:
        name:
          - psmisc
    - name: Install Python libraries
      become: true
      yum:
        name:
          - python-setuptools
          - python34-pip
          - python34-devel
          - python34-setuptools
    - name: Install python3-psutil package
      become: true
      pip:
        executable: pip3.4
        name:
          - psutil
        version: "5.6.7"
    - name: Add configuration for receiving rsyslog messages
      become: true
      lineinfile:
       path: /etc/rsyslog.conf
       line: "{{ item }}"
       state: present
      with_items:
        - '$ModLoad imudp'
        - '$UDPServerRun 514'
        - '$ModLoad imtcp'
        - '$InputTCPServerRun 514'
    - name: Restart rsyslog
      become: true
      systemd:
        name: rsyslog
        daemon_reload: yes
        state: restarted
    - name: Copy monitoring script
      become: true
      copy:
        src: ./config/monitor.py
        dest: /usr/local/bin/monitor
        mode: 0755
    - name: Copy benchmarking script
      become: true
      copy:
        src: ./config/rate-syslog-bench.sh
        dest: /usr/local/bin/rate-syslog-bench
        mode: 0755
