---
- hosts: collector
  tasks:
    - name: baseline syslog benchmark
      shell: rate-syslog-bench -s 300 -r 0
    - name: Generating 500 lines/sec syslog benchmark
      shell: rate-syslog-bench -s 300 -r 500
    - name: Generating 1000 lines/sec syslog benchmark
      shell: rate-syslog-bench -s 300 -r 1000
    - name: Generating 1500 lines/sec syslog benchmark
      shell: rate-syslog-bench -s 300 -r 1500
    - name: Find benchmarking result files
      find:
        paths: /home/{{ ansible_env.USER }}/
        patterns: [ '*.tsv' ]
      register: file_list

    - name: fetch result files in directory
      fetch:
        src: "{{ item.path }}"
        dest: ./output/
      with_items: "{{ file_list.files }}"
