- name: install fluent-bit GPG key
  become: yes
  rpm_key:
    state: present
    key: https://packages.fluentbit.io/fluentbit.key
- name: Install td-fluent-bit.repo
  become: yes
  copy:
    src: ./config/td-agent-bit.repo
    dest: /etc/yum.repos.d/td-agent-bit.repo
- name: Check if td-agent-bit is installed
  command: rpm -ql td-agent-bit
  register: td_agent_bit_check_rpm
  failed_when: td_agent_bit_check_rpm.rc > 1
  changed_when: td_agent_bit_check_rpm.rc == 1
- name: Install td-agent-bit
  become: true
  yum:
    name:
      - td-agent-bit
    state: present
- name: Copy collector configuration
  become: true
  copy:
    src: ./config/td-agent-bit.conf
    dest: /home/{{ ansible_env.USER }}/td-agent-bit.conf
- name: Make sure a td-agent-bit service is stopped
  become: true
  systemd:
    state: stopped
    daemon_reload: yes
    name: td-agent-bit
