- name: install fluent-bit GPG key
  become: yes
  rpm_key:
    state: present
    key: https://packages.fluentbit.io/fluentbit.key
- name: Install td-fluent-bit.repo
  become: yes
  copy:
    src: ./config/td-agent-bit.repo
    dest: /etc/yum.repos.d/td-agent-bit.repo
    mode: 0644
- name: Check if td-agent-bit is installed
  become: true
  yum:
    name: td-agent-bit
    state: installed
  check_mode: true
- name: Install td-agent-bit
  become: true
  yum:
    name:
      - td-agent-bit
    state: present
- name: Copy collector configuration
  become: true
  copy:
    src: ./config/td-agent-bit.conf
    dest: /home/{{ ansible_env.USER }}/td-agent-bit.conf
    mode: 0644
- name: Make sure a td-agent-bit service is stopped
  become: true
  systemd:
    state: stopped
    daemon_reload: yes
    name: td-agent-bit
