- name: Install syslog-ng
  become: true
  yum:
    name: syslog-ng
    state: present
- name: Install Development tools
  become: true
  yum:
    name:
      - "@Development tools"
    state: present
- name: Install psmisc package
  become: true
  yum:
    name:
      - psmisc
    state: present
- name: Install python3-psutil package
  become: true
  yum:
    name:
      - python38-psutil
    state: present
- name: Add configuration for receiving rsyslog messages
  become: true
  lineinfile:
   path: /etc/rsyslog.conf
   line: "{{ item }}"
   state: present
  with_items:
    - '$ModLoad imudp'
    - '$UDPServerRun 514'
    - '$ModLoad imtcp'
    - '$InputTCPServerRun 514'
- name: Restart rsyslog
  become: true
  systemd:
    name: rsyslog
    daemon_reload: yes
    state: restarted
- name: Copy monitoring script
  become: true
  copy:
    src: ./config/monitor.py
    dest: /usr/local/bin/monitor
    mode: 0755
- name: Copy benchmarking script
  become: true
  copy:
    src: ./config/rate-syslog-bench.sh
    dest: /usr/local/bin/rate-syslog-bench
    mode: 0755
