---
- hosts: aggregator
  vars_files:
    - version.yml
  tasks:
    - name: install Calyptia-Fluentd GPG key
      become: yes
      rpm_key:
        state: present
        key: https://calyptia-fluentd.s3.us-east-2.amazonaws.com/GPG-KEY-calyptia-fluentd.asc
    - name: Download calyptia-fluentd
      get_url:
        url="https://{{ calyptia_fluentd_repo }}/calyptia-fluentd-1.0.0-1.el8.x86_64.rpm"
        dest="/home/{{ ansible_env.USER }}/calyptia-fluentd-{{ calyptia_fluentd_version }}.el8.x86_64.rpm"
    - name: Install calyptia-fluentd
      become: true
      yum:
        name: /home/{{ ansible_env.USER }}/calyptia-fluentd-{{ calyptia_fluentd_version }}.el8.x86_64.rpm
        state: present
    - name: Copy aggregator configuration
      become: true
      copy:
        src: ./config/fluent-aggregator.conf
        dest: /etc/calyptia-fluentd/calyptia-fluentd.conf
    - name: Make sure a calyptia-fluentd service is restarted
      become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: calyptia-fluentd
