---
- hosts: collector
  vars_files:
    - version.yml
  tasks:
    - name: Check if calyptia-fluentd is installed
      command: dpkg-query -W calyptia-fluentd
      register: calyptia_fluentd_check_deb
      failed_when: calyptia_fluentd_check_deb.rc > 1
      changed_when: calyptia_fluentd_check_deb.rc == 1
    - name: Download calyptia-fluentd
      get_url:
        url="https://{{ calyptia_fluentd_repo }}/calyptia-fluentd_{{ calyptia_fluentd_version }}_amd64.deb"
        dest="/home/{{ ansible_env.USER }}/calyptia-fluentd_{{ calyptia_fluentd_version }}_amd64.deb"
      when: calyptia_fluentd_check_deb.rc == 1
    - name: Install python-apt
      become: true
      apt:
        name: python3-apt
    - name: Install calyptia-fluentd
      become: true
      apt:
        deb: /home/{{ ansible_env.USER }}/calyptia-fluentd_{{ calyptia_fluentd_version }}_amd64.deb
      when: calyptia_fluentd_check_deb.rc == 1
    - name: Copy collector configuration
      become: true
      copy:
        src: ./config/fluent-collector.conf
        dest: /home/{{ ansible_env.USER }}/calyptia-fluentd.conf
    - name: Make sure a calyptia-fluentd service is stopped
      become: true
      systemd:
        state: stopped
        daemon_reload: yes
        name: calyptia-fluentd
    - name: Install ruby and ruby-dev
      become: true
      apt:
        name:
          - ruby
          - ruby-dev
          - build-essential
    - name: Install Python libraries
      become: true
      apt:
        name:
          - python3-pip
          - python3-setuptools
        update_cache: yes
    - name: Install dummer via rubygems
      become: true
      gem:
        name: dummer
        version: 0.4.1
        state: present
        user_install: no
    - name: Copy dummer configuration directory
      become: true
      copy:
        src: ./config/dummer/
        dest: /home/{{ ansible_env.USER }}/dummer/
    - name: Install python3-psutil package
      become: true
      pip:
        executable: pip3
        name:
          - psutil
    - name: Copy monitoring script
      become: true
      copy:
        src: ./config/monitor.py
        dest: /usr/local/bin/monitor
        mode: 0755
    - name: Copy benchmarking script
      become: true
      copy:
        src: ./config/rate-tailing-bench.sh
        dest: /usr/local/bin/rate-tailing-bench
        mode: 0755
