---
- hosts: collector
  vars_files:
    - version.yml
  tasks:
    - name: install Calyptia-Fluentd GPG key
      become: yes
      rpm_key:
        state: present
        key: https://calyptia-fluentd.s3.us-east-2.amazonaws.com/GPG-KEY-calyptia-fluentd.asc
    - name: Download calyptia-fluentd
      get_url:
        url="https://{{ calyptia_fluentd_repo }}/calyptia-fluentd-1.0.0-1.el8.x86_64.rpm"
        dest="/home/{{ ansible_env.USER }}/calyptia-fluentd-{{ calyptia_fluentd_version }}.el8.x86_64.rpm"
    - name: Install calyptia-fluentd
      become: true
      yum:
        name: /home/{{ ansible_env.USER }}/calyptia-fluentd-{{ calyptia_fluentd_version }}.el8.x86_64.rpm
        state: present
    - name: install EPEL GPG key
      become: yes
      rpm_key:
        state: present
        key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8"
    - name: Enable EPEL
      become: true
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
    - name: Copy collector configuration
      become: true
      copy:
        src: ./config/fluent-collector.conf
        dest: /home/{{ ansible_env.USER }}/calyptia-fluentd.conf
    - name: Make sure a calyptia-fluentd service is stopped
      become: true
      systemd:
        state: stopped
        daemon_reload: yes
        name: calyptia-fluentd
    - name: Install Development tools
      become: true
      yum:
        name:
          - "@Development tools"
        state: present
    - name: Install ruby and ruby-devel
      become: true
      yum:
        name:
          - ruby
          - ruby-devel
        state: present
    - name: Install Python libraries
      become: true
      yum:
        name:
          - python38-pip
          - python38-setuptools
        state: present
    - name: Install dummer via rubygems
      become: true
      gem:
        name: dummer
        version: 0.4.1
        state: present
        user_install: no
    - name: Copy dummer configuration directory
      become: true
      copy:
        src: ./config/dummer/
        dest: /home/{{ ansible_env.USER }}/dummer/
    - name: Install python3-psutil package
      become: true
      pip:
        executable: pip3
        name:
          - psutil
    - name: Copy monitoring script
      become: true
      copy:
        src: ./config/monitor.py
        dest: /usr/local/bin/monitor
        mode: 0755
    - name: Copy benchmarking script
      become: true
      copy:
        src: ./config/rate-tailing-bench.sh
        dest: /usr/local/bin/rate-tailing-bench
        mode: 0755
