---
- hosts: collector
  vars_files:
    - version.yml
  tasks:
    - name: Check if td-agent is installed
      command: dpkg-query -W td-agent
      register: td_agent_check_deb
      failed_when: td_agent_check_deb.rc > 1
      changed_when: td_agent_check_deb.rc == 1
    - name: Download td-agent
      get_url:
        url="http://packages.treasuredata.com.s3.amazonaws.com/3/ubuntu/xenial/pool/contrib/t/td-agent/td-agent_{{ td_agent_version }}_amd64.deb"
        dest="/home/{{ ansible_env.USER }}/td-agent_{{ td_agent_version }}_amd64.deb"
      when: td_agent_check_deb.rc == 1
    - name: Install python-apt
      become: true
      apt:
        name: python-apt
    - name: Install td-agent
      become: true
      apt:
        deb: /home/{{ ansible_env.USER }}/td-agent_{{ td_agent_version }}_amd64.deb
      when: td_agent_check_deb.rc == 1
    - name: Copy collector configuration
      become: true
      copy:
        src: ./config/fluent-collector.conf
        dest: /home/{{ ansible_env.USER }}/td-agent.conf
    - name: Make sure a td-agent service is stopped
      become: true
      systemd:
        state: stopped
        daemon_reload: yes
        name: td-agent
    - name: Install ruby and ruby-dev
      become: true
      apt:
        name:
          - ruby
          - ruby-dev
          - build-essential
    - name: Install Python libraries
      become: true
      apt:
        name:
          - python-pip
          - python-setuptools
          - python3-pip
          - python3-setuptools
    - name: Install dummer via rubygems
      become: true
      gem:
        name: dummer
        version: 0.4.1
        state: present
        user_install: no
    - name: Copy dummer configuration directory
      become: true
      copy:
        src: ./config/dummer/
        dest: /home/{{ ansible_env.USER }}/dummer/
    - name: Install python3-psutil package
      become: true
      pip:
        executable: pip3
        name:
          - psutil
    - name: Copy monitoring script
      become: true
      copy:
        src: ./config/monitor.py
        dest: /usr/local/bin/monitor
        mode: 0755
    - name: Copy benchmarking script
      become: true
      copy:
        src: ./config/rate-tailing-bench.sh
        dest: /usr/local/bin/rate-tailing-bench
        mode: 0755
