---
- hosts: collector
  tasks:
    - name: Generating baseline tailing benchmark
      shell: rate-tailing-bench -s 300 -r 0
    - name: Generating 500 lines/sec tailing benchmark
      shell: rate-tailing-bench -s 300 -r 500
    - name: Generating 1000 lines/sec tailing benchmark
      shell: rate-tailing-bench -s 300 -r 1000
    - name: Generating 2000 lines/sec tailing benchmark
      shell: rate-tailing-bench -s 300 -r 2000
    - name: Generating 5000 lines/sec tailing benchmark
      shell: rate-tailing-bench -s 300 -r 5000
    - name: Find benchmarking result files
      find:
        paths: /home/{{ ansible_env.USER }}/
        patterns: [ '*.tsv' ]
      register: file_list

    - name: fetch result files in directory
      fetch:
        src: "{{ item.path }}"
        dest: ./output/
      with_items: "{{ file_list.files }}"
