---
- hosts: aggregator
  vars:
    td_agent_version: "3.7.1-0"
  tasks:
    - name: Check if td-agent is installed
      command: dpkg-query -W td-agent
      register: td_agent_check_deb
      failed_when: td_agent_check_deb.rc > 1
      changed_when: td_agent_check_deb.rc == 1
    - name: Download td-agent
      get_url:
        url="http://packages.treasuredata.com.s3.amazonaws.com/3/ubuntu/xenial/pool/contrib/t/td-agent/td-agent_{{ td_agent_version }}_amd64.deb"
        dest="/home/{{ ansible_env.USER }}/td-agent_{{ td_agent_version }}_amd64.deb"
      when: td_agent_check_deb.rc == 1
    - name: Install td-agent
      become: true
      apt: deb="/home/{{ ansible_env.USER }}/td-agent_{{ td_agent_version }}_amd64.deb"
      when: td_agent_check_deb.rc == 1
    - name: Copy aggregator configuration
      become: true
      copy:
        src: ./config/fluent-aggregator.conf
        dest: /etc/td-agent/td-agent.conf
    - name: Make sure a td-agent service is restarted
      become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: td-agent
