---
- hosts: windows
  vars:
    td_agent_version: "3.7.0-0"
    eventlog_bencher_version: "v0.3.1.1"
  tasks:
    - name: Install td-agent
      win_package:
        path="http://packages.treasuredata.com.s3.amazonaws.com/3/windows/td-agent-{{ td_agent_version }}-x64.msi"
        Product_Id="76dcb0b2-81ad-4a07-bf3b-1db567594171"
        arguments="/q"
    - name: Copy collector configuration
      win_copy:
        src: ./config/fluent-collector.conf
        dest: C:\opt\td-agent\fluent-collector.conf
    - name: Install EventLog benchmarking tool
      win_get_url:
        url: https://github.com/cosmo0920/EventLogBencher/releases/download/{{ eventlog_bencher_version }}/EventLogBencher.zip
        dest: C:\terraform\EventLogBencher.zip
    - name: Decompress zip file
      win_unzip:
        src: C:\terraform\EventLogBencher.zip
        dest: C:\tools\EventLogBencher
        delete_archive: yes
    # Just for creating benchmark channel
    - name: Create Benchmark channel
      win_shell: C:\tools\EventLogBencher\EventLogBencher.exe -w 0 -t 1 -l 512
