- name: Install Development tools
  become: true
  yum:
    name:
      - "@Development tools"
    state: present
- name: Install ruby and ruby-devel
  become: true
  yum:
    name:
      - ruby
      - ruby-devel
    state: present
- name: Install Python libraries
  become: true
  yum:
    name:
      - python38-pip
      - python38-setuptools
    state: present
- name: Install dummer via rubygems
  become: true
  gem:
    name: dummer
    version: 0.4.1
    state: present
    user_install: no
- name: Copy dummer configuration directory
  become: true
  copy:
    src: ./config/dummer/
    dest: /home/{{ ansible_env.USER }}/dummer/
- name: Install python3-psutil package
  become: true
  pip:
    executable: pip3
    name:
      - psutil
- name: Copy monitoring script
  become: true
  copy:
    src: ./config/monitor.py
    dest: /usr/local/bin/monitor
    mode: 0755
- name: Copy benchmarking script
  become: true
  copy:
    src: ./config/rate-tailing-bench.sh
    dest: /usr/local/bin/rate-tailing-bench
    mode: 0755
