- name: install TD-Agent GPG key
  become: yes
  rpm_key:
    state: present
    key: http://packages.treasuredata.com.s3.amazonaws.com/GPG-KEY-td-agent
- name: Download td-agent
  get_url:
    url="http://packages.treasuredata.com.s3.amazonaws.com/4/redhat/8/x86_64/td-agent-4.1.1-1.el8.x86_64.rpm"
    dest="/home/{{ ansible_env.USER }}/td-agent-{{ td_agent_version }}.el8.x86_64.rpm"
- name: Install td-agent
  become: true
  yum:
    name: /home/{{ ansible_env.USER }}/td-agent-{{ td_agent_version }}.el8.x86_64.rpm
    state: present
- name: Copy collector configuration
  become: true
  copy:
    src: ./config/fluent-collector.conf
    dest: /home/{{ ansible_env.USER }}/td-agent.conf
- name: Make sure a td-agent service is stopped
  become: true
  systemd:
    state: stopped
    daemon_reload: yes
    name: td-agent
